/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Validators.NumbersInStringValidator;
import design.DBConn;
import static gui.createSessionForm.studioNumber;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Etti
 */
public class addRoom extends javax.swing.JFrame {

    private static final String dbc = "jdbc:ucanaccess://src/DB.accdb;COLUMNORDER=DISPLAY";
    private static String addRoom;
    public static String studioName = null;
    public static Integer studioNumber;

    /**
     * Creates new form addRoom
     */
    public addRoom(String studioName) {
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        this.studioName = studioName;

        ResultSet result = DBConn.query("select recordingStudio.studioNumber from recordingStudio Where studioName=\"" + studioName + "\"");
        try {
            while (result.next()) {
                studioNumber = result.getInt("studioNumber");
            }
        } catch (SQLException ex) {
            Logger.getLogger(createSessionForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add = new javax.swing.JButton();
        renting = new javax.swing.JTextField();
        maxMusi = new javax.swing.JTextField();
        exit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        thereIs = new javax.swing.JCheckBox();
        stop = new javax.swing.JButton();
        bak = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/106-128.png"))); // NOI18N
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 70, 70));

        renting.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rentingKeyTyped(evt);
            }
        });
        getContentPane().add(renting, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 80, -1));

        maxMusi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                maxMusiKeyTyped(evt);
            }
        });
        getContentPane().add(maxMusi, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 80, -1));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download (3).jpg"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 30, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("add Room Form");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 220, -1));

        thereIs.setText("there is?");
        getContentPane().add(thereIs, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 80, -1));

        stop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download (4).jpg"))); // NOI18N
        stop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stopMouseClicked(evt);
            }
        });
        getContentPane().add(stop, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 30, 30));

        bak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back-button_1.jpg"))); // NOI18N
        bak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bakMouseClicked(evt);
            }
        });
        getContentPane().add(bak, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 100, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("rentingPerHour");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("maxMusicianNumber");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("recordingCell");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.jpg"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 420, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed

        addRoom = "INSERT INTO studioRoomes ([studioNumber],[rentingPerHour],[maxMusicianNumber],[recordingCell]) VALUES (?,?,?,?)";
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            try (Connection conn = DriverManager.getConnection(dbc);
                    PreparedStatement stmt1 = conn.prepareStatement(addRoom);) {
                {
                    stmt1.setInt(1, studioNumber);
                    stmt1.setInt(2, Integer.parseInt(renting.getText()));
                    stmt1.setInt(3, Integer.parseInt(maxMusi.getText()));
                    stmt1.setBoolean(4, thereIs.isSelected());
                    stmt1.executeUpdate();

                    int n = stmt1.getUpdateCount();
                    System.out.println(n + "  room inserted");
                    if (n == 1) {

                        JOptionPane.showMessageDialog(null, "room Inserted", "Insert", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(null, "room is Not Inserted", "Not Insert", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

    private void bakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bakMouseClicked
        this.setVisible(false);
        new navigtionRepForm().setVisible(true);
    }//GEN-LAST:event_bakMouseClicked

    private void stopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stopMouseClicked
        design.Design.player.close();
    }//GEN-LAST:event_stopMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        this.dispose();
    }//GEN-LAST:event_exitMouseClicked

    private void rentingKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rentingKeyTyped
        if (!renting.getText().isEmpty()) {
            Validators.NumbersInStringValidator rrr = new NumbersInStringValidator();
            rrr.isTrue(renting.getText());
        }
    }//GEN-LAST:event_rentingKeyTyped

    private void maxMusiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_maxMusiKeyTyped
        if (!maxMusi.getText().isEmpty()) {
            Validators.NumbersInStringValidator rrr = new NumbersInStringValidator();
            rrr.isTrue(maxMusi.getText());
        }
    }//GEN-LAST:event_maxMusiKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton bak;
    private javax.swing.JLabel bg;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField maxMusi;
    private javax.swing.JTextField renting;
    private javax.swing.JButton stop;
    private javax.swing.JCheckBox thereIs;
    // End of variables declaration//GEN-END:variables
}
