/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import Validators.CharValidator;
import Validators.EmailValidator;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.util.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import Validators.IdValldator;
import Validators.NumbersInStringValidator;
/**
 *
 * @author Etti
 */
public class addSoundmen extends javax.swing.JFrame {
private static final String dbc ="jdbc:ucanaccess://src/DB.accdb;COLUMNORDER=DISPLAY";
    private String sql_InsertToProfessionalSoundMan;
    private String sql_InsertToFreelancer;

    /**
     * Creates new form addSoundmen
     */
    public addSoundmen() {
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imprest = new javax.swing.JTextField();
        mixTechnician = new javax.swing.JCheckBox();
        recordProducer = new javax.swing.JCheckBox();
        head = new javax.swing.JLabel();
        masterTechnician = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        bak = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        firstName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bd = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        lastName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        file = new javax.swing.JButton();
        picture = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        imageLink = new javax.swing.JTextField();
        birthDate = new org.jdesktop.swingx.JXDatePicker();
        stageName = new javax.swing.JTextField();
        mail = new javax.swing.JTextField();
        freelancerId = new javax.swing.JTextField();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imprest.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                imprestKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                imprestKeyTyped(evt);
            }
        });
        getContentPane().add(imprest, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 110, -1));

        mixTechnician.setText("mixTechnician");
        getContentPane().add(mixTechnician, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        recordProducer.setText("recordProducer");
        getContentPane().add(recordProducer, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));

        head.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        head.setForeground(new java.awt.Color(255, 255, 255));
        head.setText("add soundmen form");
        getContentPane().add(head, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        masterTechnician.setText("masterTechnician");
        getContentPane().add(masterTechnician, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("imperst");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download (4).jpg"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 30, 30));

        bak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back-button.jpg"))); // NOI18N
        bak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bakMouseClicked(evt);
            }
        });
        getContentPane().add(bak, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 90, 40));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download (3).jpg"))); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 30, 30));

        firstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                firstNameKeyTyped(evt);
            }
        });
        getContentPane().add(firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 110, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("lastName");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        bd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bd.setForeground(new java.awt.Color(255, 255, 255));
        bd.setText("birthDate");
        getContentPane().add(bd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adds.png"))); // NOI18N
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 80, 80));

        lastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lastNameKeyTyped(evt);
            }
        });
        getContentPane().add(lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 110, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("firstName");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("E-mail");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        file.setText("choose file");
        file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileActionPerformed(evt);
            }
        });
        getContentPane().add(file, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        picture.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        picture.setForeground(new java.awt.Color(255, 255, 255));
        picture.setText("show picture here");
        getContentPane().add(picture, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 160, 150));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("stageName");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 90, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));
        getContentPane().add(imageLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 80, -1));
        getContentPane().add(birthDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));
        getContentPane().add(stageName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 110, -1));

        mail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mailKeyTyped(evt);
            }
        });
        getContentPane().add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 110, -1));

        freelancerId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                freelancerIdMousePressed(evt);
            }
        });
        getContentPane().add(freelancerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 110, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.jpg"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        String freelancerId=this.freelancerId.getText();
        String firstName=this.firstName.getText();
        String lastName=this.lastName.getText();
        Date birthDate = this.birthDate.getDate();
        String mail=this.mail.getText();     
        String stageName= this.stageName.getText();
        BufferedImage image=null;
        File file=new File(imageLink.getText());  
        
        sql_InsertToFreelancer= "INSERT INTO freelancer ([freelancerId],[firstName],[lastName],[birthDate],[mail],[stageName],[photo]) VALUES (?, ?,?, ?,?, ?,?)";
    FileInputStream fin=null;
        try {
           fin = new FileInputStream(file);
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        }

      try {//insert new artist
             Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
                try (Connection conn = DriverManager.getConnection(dbc);
                        PreparedStatement stmt = conn.prepareStatement(sql_InsertToFreelancer);
                        
                        ){{
                        stmt.setString(1,freelancerId);
                        stmt.setString(2,firstName);
                        stmt.setString(3,lastName);
                        stmt.setString(4,birthDate.toString());
                        stmt.setString(5,mail);
                        stmt.setString(6,stageName);
                        stmt.setBinaryStream(7,(InputStream)fin,(int)file.length());
                        stmt.executeUpdate();
                        int n= stmt.getUpdateCount();
                        conn.close();
                    System.out.println(n+"  recoared inserted");
                            if(n==1)
                                JOptionPane.showMessageDialog(null,"Recoared Inserted","Insert",JOptionPane.INFORMATION_MESSAGE);
                            else
                                JOptionPane.showMessageDialog(null,"Recoared is Not Inserted","Not Insert",JOptionPane.INFORMATION_MESSAGE);
                                }
                        } 
                     catch (SQLException e) {
                        e.printStackTrace();
                     }
                
                 } catch (ClassNotFoundException e) {
                e.printStackTrace();
            }


        String ID=this.freelancerId.getText();
        String imprest=this.imprest.getText();
        sql_InsertToProfessionalSoundMan= "INSERT INTO professionalSoundMan ([ID],[mixTechnician],[masterTechnician],[recordProducer],[imprest]) VALUES (?, ?,?, ?,?)";
      try {//insert new soundmen
             Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
                try (Connection conn = DriverManager.getConnection(dbc);
                        PreparedStatement stmt = conn.prepareStatement(sql_InsertToProfessionalSoundMan);
                        
                        ){{
                        stmt.setString(1,ID);
                        stmt.setBoolean(2,mixTechnician.isSelected());
                        stmt.setBoolean(3,masterTechnician.isSelected());
                        stmt.setBoolean(4,recordProducer.isSelected());
                        stmt.setString(5,imprest);
                        stmt.executeUpdate();
                        int n= stmt.getUpdateCount();
                        conn.close();
                    System.out.println(n+"  recoared inserted");
                            if(n==1)
                                JOptionPane.showMessageDialog(null,"Recoared Inserted","Insert",JOptionPane.INFORMATION_MESSAGE);
                            else
                                JOptionPane.showMessageDialog(null,"Recoared is Not Inserted","Not Insert",JOptionPane.INFORMATION_MESSAGE);
                                }
                        } 
                     catch (SQLException e) {
                        e.printStackTrace();
                     }
                
                 } catch (ClassNotFoundException e) {
                e.printStackTrace();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

    private void fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileActionPerformed
        JFileChooser filechooser= new JFileChooser();
         filechooser.setDialogTitle("Choose Your File");
         filechooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
                 //below codes for select  the file 
           int returnval=filechooser.showOpenDialog(this);
          if(returnval==JFileChooser.APPROVE_OPTION)
         {
               File file = filechooser.getSelectedFile();
               BufferedImage bi;
          try
              {   //display the image in jlabel
                bi=ImageIO.read(file);
               picture.setText("");
               imageLink.setText(file.getPath());
               picture.setIcon(new ImageIcon(bi));
        }
        catch(IOException e)
        {

        }
    }        // TODO add your handling code here:
          // TODO add your handling code here:
    }//GEN-LAST:event_fileActionPerformed

    private void bakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bakMouseClicked
       this.setVisible(false);
       new navigtionRepForm().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_bakMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        design.Design.player.close();  
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
            this.dispose();   
    }//GEN-LAST:event_jButton3MouseClicked

    private void freelancerIdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_freelancerIdMousePressed
       if(!freelancerId.getText().isEmpty())
           Validators.IdValldator.inTerface(freelancerId.getText());
    }//GEN-LAST:event_freelancerIdMousePressed

    private void imprestKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_imprestKeyPressed
                // TODO add your handling code here:
    }//GEN-LAST:event_imprestKeyPressed

    private void imprestKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_imprestKeyTyped
        if (!imprest.getText().isEmpty()) {
            Validators.NumbersInStringValidator rrr = new NumbersInStringValidator();
            rrr.isTrue(imprest.getText());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_imprestKeyTyped

    private void firstNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstNameKeyTyped
        if (!firstName.getText().isEmpty()) {
            Validators.CharValidator s = new CharValidator();
            s.isWord(firstName.getText());
        }
    }//GEN-LAST:event_firstNameKeyTyped

    private void lastNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastNameKeyTyped
        if(!lastName.getText().isEmpty()){
            Validators.CharValidator r = new CharValidator();
            r.isWord(lastName.getText());
        }
    }//GEN-LAST:event_lastNameKeyTyped

    private void mailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mailKeyTyped
         if(!mail.getText().isEmpty()){
             Validators.EmailValidator e = new EmailValidator();
             e.validateEmail(mail.getText());
         }
    }//GEN-LAST:event_mailKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addSoundmen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addSoundmen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addSoundmen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addSoundmen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addSoundmen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton bak;
    private javax.swing.JLabel bd;
    private javax.swing.JLabel bg;
    private org.jdesktop.swingx.JXDatePicker birthDate;
    private javax.swing.JButton file;
    private javax.swing.JTextField firstName;
    private javax.swing.JTextField freelancerId;
    private javax.swing.JLabel head;
    private javax.swing.JTextField imageLink;
    private javax.swing.JTextField imprest;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField lastName;
    private javax.swing.JTextField mail;
    private javax.swing.JCheckBox masterTechnician;
    private javax.swing.JCheckBox mixTechnician;
    private javax.swing.JLabel picture;
    private javax.swing.JCheckBox recordProducer;
    private javax.swing.JTextField stageName;
    // End of variables declaration//GEN-END:variables
}
