/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Etti
 */
public class AgentForm extends javax.swing.JFrame {

    /**
     * Creates new form AgentForm
     */
    public AgentForm() {
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        System.err.println("Activated agentForm");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agentImage = new javax.swing.JLabel();
        head = new javax.swing.JLabel();
        appRej = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        createShowForm = new javax.swing.JButton();
        back = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        agentImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images.jpg"))); // NOI18N
        getContentPane().add(agentImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 170, 110));

        head.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        head.setForeground(new java.awt.Color(255, 255, 255));
        head.setText("what do you want to do today?");
        getContentPane().add(head, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 390, -1));

        appRej.setFont(new java.awt.Font("Perpetua Titling MT", 1, 10)); // NOI18N
        appRej.setText("approved/reject shows");
        appRej.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appRejMouseClicked(evt);
            }
        });
        getContentPane().add(appRej, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 190, -1));

        jButton1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jButton1.setText("report");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 190, -1));

        createShowForm.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        createShowForm.setText("create new show");
        createShowForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createShowFormMouseClicked(evt);
            }
        });
        getContentPane().add(createShowForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 190, -1));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back-button_1.jpg"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 445, 90, 30));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.jpg"))); // NOI18N
        bg.setText("what ");
        bg.setMaximumSize(new java.awt.Dimension(600, 540));
        bg.setMinimumSize(new java.awt.Dimension(600, 540));
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bgMouseClicked(evt);
            }
        });
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 513, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseClicked
        
    }//GEN-LAST:event_bgMouseClicked

    private void createShowFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createShowFormMouseClicked
        createShowForm tmp = new createShowForm();
        this.setVisible(false);
        System.err.println("create show logged in");
        tmp.setVisible(true);        
    }//GEN-LAST:event_createShowFormMouseClicked

    private void createShowForm2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createShowForm2MouseClicked

    }//GEN-LAST:event_createShowForm2MouseClicked

    private void createShowForm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createShowForm2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createShowForm2ActionPerformed

    private void createShowFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createShowFormActionPerformed
         createShowForm tmp = new createShowForm();
        this.setVisible(false);
        System.err.println("create show logged in");
        tmp.setVisible(true);
    }//GEN-LAST:event_createShowFormActionPerformed

    private void createShowForm1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createShowForm1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_createShowForm1MouseClicked

    private void createShowForm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createShowForm1ActionPerformed
    }//GEN-LAST:event_createShowForm1ActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
      this.setVisible(false); 
      new LoginForm().setVisible(true);      }//GEN-LAST:event_backMouseClicked

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void appRejMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appRejMouseClicked
        showsOffer tmp = new showsOffer();
        this.setVisible(false);
        System.err.println("shows offer logged in");
        tmp.setVisible(true);
    }//GEN-LAST:event_appRejMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       ReportForm Rtmp = new ReportForm();
        this.setVisible(false);
        System.err.println("report logged in");
        Rtmp.setVisible(true);               // TODO add your handling code here:
              // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agentImage;
    private javax.swing.JButton appRej;
    private javax.swing.JButton back;
    private javax.swing.JLabel bg;
    private javax.swing.JButton createShowForm;
    private javax.swing.JLabel head;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
