/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Validators.EmailValidator;
import Validators.NumbersInStringValidator;
import static design.Design.player;
import java.awt.image.BufferedImage;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javazoom.jl.decoder.JavaLayerException;
import javazoom.jl.player.Player;
import exceptions.*;

/**
 *
 * @author Etti
 */
public class artistSignIn extends javax.swing.JFrame {

    private static final String dbc = "jdbc:ucanaccess://src/DB.accdb;COLUMNORDER=DISPLAY";
    private String sql_InsertToArtist;

    /**
     * Creates new form artistSignIn
     */
    public artistSignIn() {
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        bio = new javax.swing.JTextField();
        picture = new javax.swing.JLabel();
        imageLink = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        bak = new javax.swing.JButton();
        password = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        facebook = new javax.swing.JTextField();
        alphnumericCode = new javax.swing.JTextField();
        vol = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        stagename = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        file = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("alphnumeric Code");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("stage name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("e-mail");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        mail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mailMousePressed(evt);
            }
        });
        mail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mailKeyTyped(evt);
            }
        });
        getContentPane().add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 120, -1));
        getContentPane().add(bio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 230, -1));

        picture.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        picture.setForeground(new java.awt.Color(255, 255, 255));
        picture.setText("show picture here");
        getContentPane().add(picture, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 180, 150));

        imageLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageLinkActionPerformed(evt);
            }
        });
        getContentPane().add(imageLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 120, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("facebook");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        bak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back-button_1.jpg"))); // NOI18N
        bak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bakMouseClicked(evt);
            }
        });
        getContentPane().add(bak, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 100, 40));

        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passwordMousePressed(evt);
            }
        });
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordKeyTyped(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 120, -1));

        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adds.png"))); // NOI18N
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 80, 80));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("password");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));
        getContentPane().add(facebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 120, -1));
        getContentPane().add(alphnumericCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 120, -1));

        vol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download (4).jpg"))); // NOI18N
        vol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volMouseClicked(evt);
            }
        });
        getContentPane().add(vol, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 40, 30));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download (3).jpg"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 30, 30));
        getContentPane().add(stagename, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 120, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("BIO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 40, -1));

        file.setText("choose file");
        file.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fileMouseClicked(evt);
            }
        });
        file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileActionPerformed(evt);
            }
        });
        getContentPane().add(file, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("add new artist form");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 300, 20));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.jpg"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imageLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageLinkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imageLinkActionPerformed

    private void fileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fileMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_fileMouseClicked

    private void fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileActionPerformed
        JFileChooser filechooser = new JFileChooser();
        filechooser.setDialogTitle("Choose Your File");
        filechooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        //below codes for select  the file 
        int returnval = filechooser.showOpenDialog(this);
        if (returnval == JFileChooser.APPROVE_OPTION) {
            File file = filechooser.getSelectedFile();
            BufferedImage bi;
            try {   //display the image in jlabel
                bi = ImageIO.read(file);
                picture.setText("");
                imageLink.setText(file.getPath());
                picture.setIcon(new ImageIcon(bi));
            } catch (IOException e) {

            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_fileActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed

        String alphnumericCode = this.alphnumericCode.getText();
        String stageName = stagename.getText();
        String email = mail.getText();
        URL f = null;
        try {
            f = new URL(facebook.getText());
        } catch (MalformedURLException ex) {
            ex.printStackTrace();
        }
        BufferedImage image = null;
        File file = new File(imageLink.getText());

        sql_InsertToArtist = "INSERT INTO artist ([alphnumericCode],[stageName],[facebookPage],[E-mail],[password],[photo]) VALUES (?, ?,?, ?,?, ?)";
        FileInputStream fin = null;
        try {
            fin = new FileInputStream(file);
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        }
        String pass = password.getText();

        try {//insert new artist
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            try (Connection conn = DriverManager.getConnection(dbc);
                    PreparedStatement stmt = conn.prepareStatement(sql_InsertToArtist);) {
                {
                    stmt.setString(1, alphnumericCode);
                    stmt.setString(2, stageName);
                    stmt.setURL(3, f);
                    stmt.setString(4, email);
                    stmt.setString(5, pass);
                    stmt.setBinaryStream(6, (InputStream) fin, (int) file.length());
                    stmt.executeUpdate();
                    int n = stmt.getUpdateCount();
                    conn.close();
                    System.out.println(n + "  recoared inserted");
                    if (n == 1) {
                        JOptionPane.showMessageDialog(null, "Recoared Inserted", "Insert", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(null, "Recoared is Not Inserted", "Not Insert", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }

        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_addActionPerformed

    private void bakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bakMouseClicked
        this.setVisible(false);
        new LoginForm().setVisible(true);
    }//GEN-LAST:event_bakMouseClicked

    private void volMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volMouseClicked
        design.Design.player.close();
    }//GEN-LAST:event_volMouseClicked

    private void passwordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMousePressed
        JOptionPane.showMessageDialog(null, "use only numbers");        // TODO add your handling code here:
    }//GEN-LAST:event_passwordMousePressed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_exitMouseClicked

    private void mailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mailKeyTyped

    }//GEN-LAST:event_mailKeyTyped
 
    private void passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyTyped
             if (!password.getText().isEmpty()) {
            Validators.NumbersInStringValidator rrr = new NumbersInStringValidator();
            rrr.isTrue(password.getText());
             }
    }//GEN-LAST:event_passwordKeyTyped

    private void mailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mailMousePressed
                 if(!mail.getText().isEmpty()){
             Validators.EmailValidator e = new EmailValidator();
             e.validateEmail(mail.getText());    
                 }        // TODO add your handling code here:
    }//GEN-LAST:event_mailMousePressed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField alphnumericCode;
    private javax.swing.JButton bak;
    private javax.swing.JLabel bg;
    private javax.swing.JTextField bio;
    private javax.swing.JButton exit;
    private javax.swing.JTextField facebook;
    private javax.swing.JButton file;
    private javax.swing.JTextField imageLink;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField password;
    private javax.swing.JLabel picture;
    private javax.swing.JTextField stagename;
    private javax.swing.JButton vol;
    // End of variables declaration//GEN-END:variables
}
