/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import design.DBConn;
import design.Design;
import entity.Artist;
import entity.Show;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author Etti
 */
public class createShowForm extends javax.swing.JFrame {
    
   
   ResultSet rs = null;

    /**
     * Creates new form createShow
     */
    public createShowForm() {
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        System.err.println("Activated createShowForm");
     try
    {    
        ResultSet rs = Design.getCon().query("select * from Artist Where Artist.agentId=\""+DBConn.getAgentConnected().getAgentID()+"\"");
        jComboBoxArtists.removeAllItems();
        jComboBoxArtists.addItem("Select Main Artist");
     
        while(rs.next()){
            String alphanumericCode = rs.getString("alphanumericCode");
            String stageName = rs.getString("stageName");
            
            jComboBoxArtists.addItem(stageName);
        }
        
        ResultSet res = DBConn.query("Select showPlace.placeNumber, Agent.agentId\n"+
         "Form showPlace INNER JOIN (Agent INNER JOIN agentChoosePlace ON Agent.agentId = agentChoosePlace.agentId) ON showPlace.placeNumber = agentChoosePlace.placeNumber\n"+
         "WHERE (((Agent.agentId)=[agentChoosePlace].[agentId]) AND ((showPalce.placeNumber)=[agentChoosePlace].[showPlace])AND ((Agent.agentId)))="+DBConn.getAgentConnected().getAgentID());
         jComboBoxPlaces.removeAllItems();
         jComboBoxPlaces.addItem("Select show place");
             
         while(res.next()){
            // String 
         }
            } catch (SQLException ex){
                 Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
    
        }
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lblheadForm = new javax.swing.JLabel();
        mainArtist = new javax.swing.JLabel();
        jComboBoxArtists = new javax.swing.JComboBox<>();
        lblimageMainArtist = new javax.swing.JLabel();
        showPlace = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxPlaces = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtArtistName = new javax.swing.JTextField();
        txtPlace = new javax.swing.JTextField();
        listOtherArtists = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jComboBoxOtherArtists = new javax.swing.JComboBox<>();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblheadForm.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        lblheadForm.setForeground(new java.awt.Color(255, 255, 255));
        lblheadForm.setText("create new show form");
        getContentPane().add(lblheadForm);
        lblheadForm.setBounds(20, 40, 340, 40);

        mainArtist.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        mainArtist.setForeground(new java.awt.Color(255, 255, 255));
        mainArtist.setText("choose your main artist ");
        getContentPane().add(mainArtist);
        mainArtist.setBounds(110, 100, 240, 30);

        jComboBoxArtists.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxArtists.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxArtistsItemStateChanged(evt);
            }
        });
        jComboBoxArtists.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxArtistsActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxArtists);
        jComboBoxArtists.setBounds(340, 100, 70, 20);

        lblimageMainArtist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plus.jpg"))); // NOI18N
        getContentPane().add(lblimageMainArtist);
        lblimageMainArtist.setBounds(40, 90, 50, 50);

        showPlace.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        showPlace.setForeground(new java.awt.Color(255, 255, 255));
        showPlace.setText("choose show place");
        getContentPane().add(showPlace);
        showPlace.setBounds(110, 170, 170, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plus.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 150, 50, 50);

        jComboBoxPlaces.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxPlaces.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxPlacesItemStateChanged(evt);
            }
        });
        jComboBoxPlaces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPlacesActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxPlaces);
        jComboBoxPlaces.setBounds(340, 170, 70, 20);

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("invite other artists (only if you want)");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 340, 370, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plus.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 330, 60, 60);

        txtArtistName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArtistNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtArtistName);
        txtArtistName.setBounds(110, 130, 80, 20);

        txtPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlaceActionPerformed(evt);
            }
        });
        getContentPane().add(txtPlace);
        txtPlace.setBounds(110, 200, 80, 20);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listOtherArtists.setViewportView(jList1);

        getContentPane().add(listOtherArtists);
        listOtherArtists.setBounds(220, 370, 35, 100);

        jButton1.setText("add");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(430, 470, 51, 23);

        jComboBoxOtherArtists.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxOtherArtists.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxOtherArtistsItemStateChanged(evt);
            }
        });
        jComboBoxOtherArtists.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOtherArtistsActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxOtherArtists);
        jComboBoxOtherArtists.setBounds(100, 370, 80, 20);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.jpg"))); // NOI18N
        getContentPane().add(bg);
        bg.setBounds(0, -10, 530, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxOtherArtistsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOtherArtistsActionPerformed
    }//GEN-LAST:event_jComboBoxOtherArtistsActionPerformed

    private void jComboBoxOtherArtistsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxOtherArtistsItemStateChanged

    }//GEN-LAST:event_jComboBoxOtherArtistsItemStateChanged

    private void txtPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlaceActionPerformed

    private void jComboBoxArtistsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxArtistsActionPerformed
        
    }//GEN-LAST:event_jComboBoxArtistsActionPerformed

    private void txtArtistNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArtistNameActionPerformed
        
    }//GEN-LAST:event_txtArtistNameActionPerformed

    private void jComboBoxArtistsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxArtistsItemStateChanged
        //fix txtArtistName.setText(jComboBoxArtists.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBoxArtistsItemStateChanged

    private void jComboBoxPlacesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPlacesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPlacesActionPerformed

    private void jComboBoxPlacesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxPlacesItemStateChanged
        txtPlace.setText(jComboBoxPlaces.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBoxPlacesItemStateChanged

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Show newShow = new Show(txtArtistName.getText(), txtPlace.getText());
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createShowForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createShowForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createShowForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createShowForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new createShowForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxArtists;
    private javax.swing.JComboBox<String> jComboBoxOtherArtists;
    private javax.swing.JComboBox<String> jComboBoxPlaces;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblheadForm;
    private javax.swing.JLabel lblimageMainArtist;
    private javax.swing.JScrollPane listOtherArtists;
    private javax.swing.JLabel mainArtist;
    private javax.swing.JLabel showPlace;
    private javax.swing.JTextField txtArtistName;
    private javax.swing.JTextField txtPlace;
    // End of variables declaration//GEN-END:variables
}
