/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import design.DBConn;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Etti
 */
public class createRecordForm extends javax.swing.JFrame {

    JFrame form;
    String artId;
    private static final String dbc = "jdbc:ucanaccess://src/DB.accdb;COLUMNORDER=DISPLAY";
    private String sql_InsertToRecord;
    private static String sql_AddRecordingToSession = "";

    /**
     * Creates new form createRecordForm
     */
    public createRecordForm(JFrame form, String ANumber) {
        this.form = form;
        this.artId = ANumber;
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);

        status.removeAllItems();
        status.addItem("Select status");
        status.addItem("frame");
        status.addItem("demo");
        status.addItem("masterd");
        lastRecordNumber.removeAllItems();
        lastRecordNumber.addItem("Select lastRecordNumber");

        System.err.println("Activated createRecordForm");

        try {
            ResultSet rs = DBConn.query("SELECT record.recordNumber \n"
                    + "FROM record");
            lastRecordNumber.removeAllItems();
            lastRecordNumber.addItem("Select record");
            while (rs.next()) {
                String recordNumber = rs.getString("recordNumber");
                lastRecordNumber.addItem(recordNumber);
            }

            ResultSet res = DBConn.query("SELECT recordingSessions.sessionNumber\n"
                    + "FROM recordingSessions\n");
            sesNumber.removeAllItems();
            sesNumber.addItem("Select session");
            while (res.next()) {
                String sessionNumber = res.getString("sessionNumber");
                sesNumber.addItem(sessionNumber);
            }

        } catch (SQLException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        HEAD = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        linkToSong = new javax.swing.JTextField();
        recordName = new javax.swing.JTextField();
        songDeatils = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        file = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        hour = new com.toedter.components.JSpinField();
        min = new com.toedter.components.JSpinField();
        jLabel7 = new javax.swing.JLabel();
        sessionNum = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        songName = new javax.swing.JTextField();
        lastRecordNumber = new javax.swing.JComboBox<>();
        sesNumber = new javax.swing.JComboBox<>();
        bak = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        zipLink = new javax.swing.JTextField();
        status = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        vol = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("record name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        HEAD.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        HEAD.setForeground(new java.awt.Color(255, 255, 255));
        HEAD.setText("create record form ");
        getContentPane().add(HEAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 320, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("link to song deatils");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        getContentPane().add(linkToSong, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 90, -1));
        getContentPane().add(recordName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 90, -1));
        getContentPane().add(songDeatils, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 90, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("zip for record");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        file.setText("choose file");
        file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileActionPerformed(evt);
            }
        });
        getContentPane().add(file, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 90, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("status");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));
        getContentPane().add(hour, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 40, -1));
        getContentPane().add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 40, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Last Record Number");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        sessionNum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sessionNum.setForeground(new java.awt.Color(255, 255, 255));
        sessionNum.setText("seesion Number");
        getContentPane().add(sessionNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("song Name");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 60, 60));
        getContentPane().add(songName, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 70, -1));

        lastRecordNumber.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(lastRecordNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 90, -1));

        sesNumber.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(sesNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 90, -1));

        bak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back-button_1.jpg"))); // NOI18N
        bak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bakMouseClicked(evt);
            }
        });
        getContentPane().add(bak, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 100, 40));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download (3).jpg"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 30, 30));
        getContentPane().add(zipLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 70, -1));

        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 90, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("link to song");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 100, -1));

        vol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download (4).jpg"))); // NOI18N
        vol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volMouseClicked(evt);
            }
        });
        getContentPane().add(vol, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 30, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("recordDuration");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.jpg"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volMouseClicked
        design.Design.player.close();
        // TODO add your handling code here:
    }//GEN-LAST:event_volMouseClicked

    private void bakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bakMouseClicked
        this.dispose();
        form.setVisible(true);
    }//GEN-LAST:event_bakMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String recordName = this.recordName.getText();
        String linkToSongDetails = this.songDeatils.getText();
        Integer recordDuration = this.hour.getComponentCount();
        String linkForSong = this.linkToSong.getText();
        String status = this.status.getSelectedItem().toString();
        String lastRecordNumber = this.lastRecordNumber.getSelectedItem().toString();
        String sessNumber = this.sesNumber.getSelectedItem().toString();
        String songName = this.songName.getText();
        BufferedImage image = null;
        File zipForRecord = new File(zipLink.getText());

        sql_InsertToRecord = "INSERT INTO record ([recordName],[linkToSongDetails],[recordDuration],[linkForSong],[zipForRecord],[status],[lastRecordNumber],[sessionNumber],[artistId],[songName]) VALUES (?,?,?,?,?,?,?,?,?,?)";
        FileInputStream fin = null;
        try {
            fin = new FileInputStream(zipForRecord);
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        }
        try {//insert new artist
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            try (Connection conn = DriverManager.getConnection(dbc);
                    PreparedStatement stmt = conn.prepareStatement(sql_InsertToRecord);) {
                {
                    stmt.setString(1, recordName);
                    stmt.setString(2, linkToSongDetails);
                    stmt.setInt(3, recordDuration);
                    stmt.setString(4, linkForSong);
                    stmt.setBinaryStream(5, (InputStream) fin, (int) zipForRecord.length());
                    stmt.setString(6, status);
                    stmt.setString(7, lastRecordNumber);
                    stmt.setString(8, sessNumber);
                    stmt.setString(9, artId);
                    stmt.setString(10, songName);
                    stmt.executeUpdate();
                    int n = stmt.getUpdateCount();
                    conn.close();
                    System.out.println(n + "  recoared inserted");
                    if (n == 1) {
                        JOptionPane.showMessageDialog(null, "Recoared Inserted", "Insert", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(null, "Recoared is Not Inserted", "Not Insert", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }

        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileActionPerformed
        JFileChooser filechooser = new JFileChooser();
        filechooser.setDialogTitle("Choose Your File");
        filechooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        //below codes for select  the file 
        int returnval = filechooser.showOpenDialog(this);
        if (returnval == JFileChooser.APPROVE_OPTION) {
            File file = filechooser.getSelectedFile();
            BufferedImage bi;
            try {   //display the image in jlabel
                bi = ImageIO.read(file);
                zipLink.setText(file.getPath());
            } catch (IOException e) {
            }
        }
    }//GEN-LAST:event_fileActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_exitMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel HEAD;
    private javax.swing.JButton bak;
    private javax.swing.JButton exit;
    private javax.swing.JButton file;
    private com.toedter.components.JSpinField hour;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> lastRecordNumber;
    private javax.swing.JTextField linkToSong;
    private com.toedter.components.JSpinField min;
    private javax.swing.JTextField recordName;
    private javax.swing.JComboBox<String> sesNumber;
    private javax.swing.JLabel sessionNum;
    private javax.swing.JTextField songDeatils;
    private javax.swing.JTextField songName;
    private javax.swing.JComboBox<String> status;
    private javax.swing.JButton vol;
    private javax.swing.JTextField zipLink;
    // End of variables declaration//GEN-END:variables
}
