/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import design.DBConn;
import java.awt.event.ItemEvent;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Etti
 */
public class inviteOtherArtistsForm extends javax.swing.JFrame {
  ResultSet result = null;
    JFrame form;
    /**
     * Creates new form inviteOtherArtistsForm
     */
    public inviteOtherArtistsForm(JFrame form, String artistNumber) {
        this.form = form;
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
    //    String ANumber = artistNumber;
       
        try {
            ResultSet res = DBConn.query("SELECT * from Artist Where Artist.agentId=\""+222222222+"\"");
                    ResultSetMetaData rsmetadate = res.getMetaData();
                    int col = rsmetadate.getColumnCount();
                    System.err.println("columns: " + col);
                    DefaultTableModel dtm = new DefaultTableModel();
                    Vector columns_name = new Vector();
                    Vector data_rows = new Vector();
                    for (int i = 1; i <= col; i++) {
                       columns_name.addElement(rsmetadate.getColumnName(i)); }
                    
                        dtm.setColumnIdentifiers(columns_name);
                    while (res.next()) {
                        data_rows = new Vector();
                        for (int j = 1; j <= col; j++) {
                        data_rows.addElement(res.getString(j)); 
                        }
                    
                    dtm.addRow(data_rows);
                    
                    }
                    jTable1.setModel(dtm);

                    } catch (Exception e) {
                       Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, e);

                }
             }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bak = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        invite = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back-button_1.jpg"))); // NOI18N
        bak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bakMouseClicked(evt);
            }
        });
        getContentPane().add(bak, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 110, 30));

        jButton1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jButton1.setText("invite");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 110, 20));

        invite.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        invite.setForeground(new java.awt.Color(255, 255, 255));
        invite.setText("apprited Artists details");
        getContentPane().add(invite, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 280, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 590, 130));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 60, 110));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.jpg"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bakMouseClicked
              this.dispose();
            form.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_bakMouseClicked

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1KeyPressed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bak;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel invite;
    private javax.swing.JButton jButton1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
