/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import design.DBConn;
import entity.CreateXML;
import entity.artist;
import entity.reprsentativeMuza;
import java.net.URISyntaxException;
import java.sql.Blob;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import gui.*;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.TransformerConfigurationException;
import javax.xml.transform.TransformerException;
/**
 *
 * @author Etti
 */
public class navigtionArtistForm extends javax.swing.JFrame {

    String ANumber = null;

    /**
     * Creates new form navigtionForm
     */
    public navigtionArtistForm(String ANumber) throws TransformerException {
        try {
            this.ANumber = ANumber;
            setUndecorated(true);
            initComponents();
            setLocationRelativeTo(null);
            
            System.err.println(""+ANumber);
            
           CreateXML.main(ANumber);
        } catch (TransformerConfigurationException ex) {
            Logger.getLogger(navigtionArtistForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParserConfigurationException ex) {
            Logger.getLogger(navigtionArtistForm.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    
  
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        head = new javax.swing.JLabel();
        watchSeesion = new javax.swing.JButton();
        createRec = new javax.swing.JButton();
        watchRec = new javax.swing.JButton();
        bak = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        vol = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        creteSession = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        head.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        head.setForeground(new java.awt.Color(255, 255, 255));
        head.setText("Artist menu");
        getContentPane().add(head, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, -1));

        watchSeesion.setText("watch Session");
        watchSeesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                watchSeesionMouseClicked(evt);
            }
        });
        watchSeesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                watchSeesionActionPerformed(evt);
            }
        });
        getContentPane().add(watchSeesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 160, -1));

        createRec.setText("create Record");
        createRec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createRecMouseClicked(evt);
            }
        });
        getContentPane().add(createRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 160, -1));

        watchRec.setText("watch Record");
        watchRec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                watchRecMouseClicked(evt);
            }
        });
        getContentPane().add(watchRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 160, -1));

        bak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back-button.jpg"))); // NOI18N
        bak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bakMouseClicked(evt);
            }
        });
        getContentPane().add(bak, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 100, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Record");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        vol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download (4).jpg"))); // NOI18N
        vol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volMouseClicked(evt);
            }
        });
        getContentPane().add(vol, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 30, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Session");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 70, 20));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download (3).jpg"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 30, 30));

        creteSession.setText("create Session");
        creteSession.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creteSessionMouseClicked(evt);
            }
        });
        getContentPane().add(creteSession, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 160, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.jpg"))); // NOI18N
        bg.setMaximumSize(new java.awt.Dimension(850, 850));
        bg.setMinimumSize(new java.awt.Dimension(750, 750));
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void watchSeesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_watchSeesionMouseClicked
        this.setVisible(false);
        new watchSession(this, ANumber).setVisible(true);
    }//GEN-LAST:event_watchSeesionMouseClicked

    private void watchSeesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_watchSeesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_watchSeesionActionPerformed

    private void bakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bakMouseClicked
        this.setVisible(false);
        new LoginForm().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_bakMouseClicked

    private void creteSessionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creteSessionMouseClicked
        this.setVisible(false);
        new createSessionForm(this, ANumber).setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_creteSessionMouseClicked

    private void createRecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createRecMouseClicked
        this.setVisible(false);
        new createRecordForm(this, ANumber).setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_createRecMouseClicked

    private void watchRecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_watchRecMouseClicked
        this.setVisible(false);
        new watchRecords(this, ANumber).setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_watchRecMouseClicked

    private void volMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volMouseClicked
        design.Design.player.close();  
    }//GEN-LAST:event_volMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(navigtionArtistForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(navigtionArtistForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(navigtionArtistForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(navigtionArtistForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bak;
    private javax.swing.JLabel bg;
    private javax.swing.JButton createRec;
    private javax.swing.JButton creteSession;
    private javax.swing.JLabel head;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton vol;
    private javax.swing.JButton watchRec;
    private javax.swing.JButton watchSeesion;
    // End of variables declaration//GEN-END:variables
}
