/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import design.DBConn;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Etti
 */
public class roomsDetails extends javax.swing.JFrame {
    
    ResultSet result;
    JFrame form;
    Integer studioNum;
    Integer sesionNum;
    Integer roomNum;
    private String sql6;
    private static final String dbc = "jdbc:ucanaccess://src/DB.accdb;COLUMNORDER=DISPLAY";


    /**
     * Creates new form PlaceDetails
     */
    public roomsDetails(JFrame form, Integer studioNumber, Integer sesionNumber) {
        this.form = form;
        this.studioNum = studioNumber;
        this.sesionNum = sesionNumber;
        System.out.println(""+sesionNum);
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        System.err.println("SESSIONMUN"+sesionNum);
        
        try {
            ResultSet result = DBConn.query("SELECT studioRoomes.*\n"
                    + "FROM studioRoomes\n"
                    + "WHERE studioRoomes.roomNumber=" +studioNum );
            ResultSetMetaData rsmetadate = result.getMetaData();
            int columns = rsmetadate.getColumnCount();
            System.err.println("columns: " + columns);
            DefaultTableModel dtm = new DefaultTableModel();
            Vector columns_name = new Vector();
            Vector data_rows = new Vector();

            for (int i = 1; i <= columns; i++) {
                columns_name.addElement(rsmetadate.getColumnName(i));
            }
            dtm.setColumnIdentifiers(columns_name);

            while (result.next()) {
                data_rows = new Vector();
                for (int j = 1; j <= columns; j++) {
                    data_rows.addElement(result.getString(j));
                }
                dtm.addRow(data_rows);
            }
            jTable1.setModel(dtm);

        } catch (Exception e) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        head = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        vol = new javax.swing.JButton();
        add = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        head.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        head.setForeground(new java.awt.Color(255, 255, 255));
        head.setText("rooms Details");
        getContentPane().add(head, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Place Number", "Place Name", "Adderss", "E-mail", "Phone", "Google-Maps", "capacity"
            }
        ));
        jTable1.setCellSelectionEnabled(true);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setRowHeight(25);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 540, 50));

        vol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download (4).jpg"))); // NOI18N
        vol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volMouseClicked(evt);
            }
        });
        vol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volActionPerformed(evt);
            }
        });
        getContentPane().add(vol, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 40, 30));

        add.setText("add");
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download (3).jpg"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 30, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back-button_1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 110, 40));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.jpg"))); // NOI18N
        bg.setMaximumSize(new java.awt.Dimension(640, 500));
        bg.setMinimumSize(new java.awt.Dimension(640, 500));
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
            this.dispose();
            form.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void volMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volMouseClicked
        design.Design.player.close();  
    }//GEN-LAST:event_volMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void volActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_volActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
   
    }//GEN-LAST:event_addActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
           roomNum = jTable1.getSelectedRow()+1;
           System.out.println(""+roomNum);
    }//GEN-LAST:event_jTable1MouseClicked

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
          System.err.println(""+sesionNum);
          System.err.println(""+studioNum);
        sql6= "INSERT INTO sessionInTheRoom ([sessionNumber], [studioNumber]) VALUES (?,?)";
         System.err.println(""+sesionNum);
                 try {
             Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
                try (Connection conn = DriverManager.getConnection(dbc);
                        PreparedStatement stmt1 = conn.prepareStatement(sql6);
                        ){{
                        stmt1.setInt(1,sesionNum);
                        stmt1.setInt(2,studioNum);
                        stmt1.executeUpdate();
                        
                        int n= stmt1.getUpdateCount();
                    System.out.println(n+"  Rooms inserted");
                            if(n==1){
                                JOptionPane.showMessageDialog(null,"Rooms Inserted","Insert",JOptionPane.INFORMATION_MESSAGE);
                            }
                            else
                                JOptionPane.showMessageDialog(null,"Rooms are Not Inserted","Not Insert",JOptionPane.INFORMATION_MESSAGE);
                        }}   
                     catch (SQLException e) {
                        e.printStackTrace();
                     }
                 } catch (ClassNotFoundException e) {
                e.printStackTrace();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_addMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel head;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton vol;
    // End of variables declaration//GEN-END:variables
}
