/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import design.DBConn;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Etti
 */
public class showsOffer extends javax.swing.JFrame {

    /**
     * Creates new form showsOffer
     */
    public showsOffer() {
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        //Integer lNumber = Integer.parseInt(locationNumber);
        System.err.println("Activated showsForm");
         try {
             
            ResultSet rs = DBConn.query("SELECT Show.showNumber, Show.dateOfShow FROM Show WHERE Show.showNumber=\""+1+"\"");
            ResultSetMetaData metadate = rs.getMetaData();
            int col = metadate.getColumnCount();
            System.err.println("columns: " + col);
            DefaultTableModel d = new DefaultTableModel();
            Vector col_name = new Vector();
            Vector data_ro = new Vector();

            for (int i = 1; i <= col; i++) {
                col_name.addElement(metadate.getColumnName(i));
            }
            d.setColumnIdentifiers(col_name);

            while (rs.next()) {
                data_ro = new Vector();
                for (int j = 1; j <= col; j++) {
                    data_ro.addElement(rs.getString(j));
                }
                d.addRow(data_ro);
            }
            ArtDet.setModel(d);
             
            ResultSet result = DBConn.query("SELECT showPlace.*\n"
                    + "FROM (showPlace INNER JOIN openPlace ON showPlace.placeNumber = openPlace.placeNumber) INNER JOIN agentChoosePlace ON showPlace.placeNumber = agentChoosePlace.placeNumber\n"
                    + "WHERE (((agentChoosePlace.agentId)=" + DBConn.getAgentConnected().getAgentID() + ") AND ((showPlace.placeNumber=" + 1 + ")));");
            ResultSetMetaData rsmetadate = result.getMetaData();
            int columns = rsmetadate.getColumnCount();
            System.err.println("columns: " + columns);
            DefaultTableModel dtm = new DefaultTableModel();
            Vector columns_name = new Vector();
            Vector data_rows = new Vector();

            for (int i = 1; i <= columns; i++) {
                columns_name.addElement(rsmetadate.getColumnName(i));
            }
            dtm.setColumnIdentifiers(columns_name);

            while (result.next()) {
                data_rows = new Vector();
                for (int j = 1; j <= columns; j++) {
                    data_rows.addElement(result.getString(j));
                }
                dtm.addRow(data_rows);
            }
            plaDet.setModel(dtm);
         
            ResultSet res = DBConn.query("SELECT * from Show Where Show.showNumber=\""+1+"\"");
            ResultSetMetaData rsmetadat = res.getMetaData();
            int column = rsmetadat.getColumnCount();
            System.err.println("columns: " + column);
            DefaultTableModel dt = new DefaultTableModel();
            Vector columns_nam = new Vector();
            Vector data_row = new Vector();

            for (int i = 1; i <= columns; i++) {
                columns_nam.addElement(rsmetadat.getColumnName(i));
            }
            dt.setColumnIdentifiers(columns_nam);

            while (res.next()) {
                data_row = new Vector();
                for (int j = 1; j <= column; j++) {
                    data_row.addElement(res.getString(j));
                }
                dt.addRow(data_row);
            }
            showDet.setModel(dt);
            // list Artists Dates
            
   
        } catch (Exception e) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        head1 = new javax.swing.JLabel();
        head = new javax.swing.JLabel();
        bak = new javax.swing.JButton();
        head2 = new javax.swing.JLabel();
        head3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        showDet = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        plaDet = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        ArtDet = new javax.swing.JTable();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        head1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        head1.setForeground(new java.awt.Color(255, 255, 255));
        head1.setText("Show details");
        getContentPane().add(head1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        head.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        head.setForeground(new java.awt.Color(255, 255, 255));
        head.setText("approve/reject shows");
        getContentPane().add(head, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 260, 30));

        bak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back-button_1.jpg"))); // NOI18N
        bak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bakMouseClicked(evt);
            }
        });
        getContentPane().add(bak, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 110, 30));

        head2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        head2.setForeground(new java.awt.Color(255, 255, 255));
        head2.setText("show place details");
        getContentPane().add(head2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 190, 30));

        head3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        head3.setForeground(new java.awt.Color(255, 255, 255));
        head3.setText("Artists schedule");
        getContentPane().add(head3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 150, -1));

        showDet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(showDet);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 590, 50));

        plaDet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane3.setViewportView(plaDet);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 580, 50));

        ArtDet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane5.setViewportView(ArtDet);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 570, 90));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.jpg"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bakMouseClicked
        this.setVisible(false); 
      new AgentForm().setVisible(true);  
    }//GEN-LAST:event_bakMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(showsOffer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(showsOffer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(showsOffer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(showsOffer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new showsOffer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ArtDet;
    private javax.swing.JButton bak;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel head;
    private javax.swing.JLabel head1;
    private javax.swing.JLabel head2;
    private javax.swing.JLabel head3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable plaDet;
    private javax.swing.JTable showDet;
    // End of variables declaration//GEN-END:variables
}
