/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author user
 */
public class ShowDetails extends javax.swing.JFrame {

    /**
     * Creates new form ShowDetails
     */
    public ShowDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblheadForm = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        lblExit = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        title1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        scrollPane1 = new java.awt.ScrollPane();
        bg2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblheadForm.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        lblheadForm.setForeground(new java.awt.Color(255, 255, 255));
        lblheadForm.setText("Show details");
        getContentPane().add(lblheadForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 190, 40));

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("Date:");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 130, 30));

        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/goback.jpg"))); // NOI18N
        lblExit.setPreferredSize(new java.awt.Dimension(60, 60));
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });
        getContentPane().add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 470, 60, 50));

        title.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("show:");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        title1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        title1.setForeground(new java.awt.Color(255, 255, 255));
        title1.setText("Revenues:");
        getContentPane().add(title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, -1, -1));

        jTextField2.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 150, 30));

        jTextField3.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 150, 30));

        jTextField4.setBackground(new java.awt.Color(0, 0, 0));
        jTextField4.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setText("Mininum Age:");
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 130, 30));

        jTextField5.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 150, 30));

        jTextField12.setBackground(new java.awt.Color(0, 0, 0));
        jTextField12.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jTextField12.setForeground(new java.awt.Color(255, 255, 255));
        jTextField12.setText("Left Tickets:");
        getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 130, 30));

        jTextField13.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 150, 30));

        jTextField14.setBackground(new java.awt.Color(0, 0, 0));
        jTextField14.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jTextField14.setForeground(new java.awt.Color(255, 255, 255));
        jTextField14.setText("Show Number:");
        getContentPane().add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 130, 30));

        jTextField15.setBackground(new java.awt.Color(0, 0, 0));
        jTextField15.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jTextField15.setForeground(new java.awt.Color(255, 255, 255));
        jTextField15.setText("Main Artist:");
        getContentPane().add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 130, 30));

        jTextField6.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 150, 30));

        jTextField16.setBackground(new java.awt.Color(0, 0, 0));
        jTextField16.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jTextField16.setForeground(new java.awt.Color(255, 255, 255));
        jTextField16.setText("place:");
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 130, 30));

        jTextField7.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 150, 30));

        jTextField17.setBackground(new java.awt.Color(0, 0, 0));
        jTextField17.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jTextField17.setForeground(new java.awt.Color(255, 255, 255));
        jTextField17.setText("Other artists:");
        getContentPane().add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 130, 30));

        jTextField8.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 150, 30));

        jTextField18.setBackground(new java.awt.Color(0, 0, 0));
        jTextField18.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jTextField18.setForeground(new java.awt.Color(255, 255, 255));
        jTextField18.setText("Agent:");
        getContentPane().add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 130, 30));

        jTextField9.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 150, 30));

        jTextField19.setBackground(new java.awt.Color(0, 0, 0));
        jTextField19.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jTextField19.setForeground(new java.awt.Color(255, 255, 255));
        jTextField19.setText("Total revenues:");
        getContentPane().add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 140, 30));

        jTextField10.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 150, 30));

        jTextField20.setBackground(new java.awt.Color(0, 0, 0));
        jTextField20.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jTextField20.setForeground(new java.awt.Color(255, 255, 255));
        jTextField20.setText("Regular Sale:");
        getContentPane().add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 140, 30));

        jTextField11.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 150, 30));

        jTextField21.setBackground(new java.awt.Color(0, 0, 0));
        jTextField21.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jTextField21.setForeground(new java.awt.Color(255, 255, 255));
        jTextField21.setText("Expenses:");
        getContentPane().add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 140, 30));

        jTextField22.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        getContentPane().add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, 150, 30));

        jTextField23.setBackground(new java.awt.Color(0, 0, 0));
        jTextField23.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jTextField23.setForeground(new java.awt.Color(255, 255, 255));
        jTextField23.setText("Balance:");
        getContentPane().add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 140, 30));

        jTextField24.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        getContentPane().add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 150, 30));

        jTextField25.setBackground(new java.awt.Color(0, 0, 0));
        jTextField25.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jTextField25.setForeground(new java.awt.Color(255, 255, 255));
        jTextField25.setText("Presale:");
        getContentPane().add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 140, 30));

        jTextField26.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        getContentPane().add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 150, 30));

        jTextField27.setBackground(new java.awt.Color(0, 0, 0));
        jTextField27.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jTextField27.setForeground(new java.awt.Color(255, 255, 255));
        jTextField27.setText("Ticket Price:");
        getContentPane().add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 130, 30));
        getContentPane().add(scrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 150, 80));

        bg2.setBackground(new java.awt.Color(0, 0, 0));
        bg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.jpg"))); // NOI18N
        bg2.setText("what ");
        bg2.setMaximumSize(new java.awt.Dimension(600, 540));
        bg2.setMinimumSize(new java.awt.Dimension(600, 540));
        bg2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bg2MouseClicked(evt);
            }
        });
        getContentPane().add(bg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void bg2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bg2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bg2MouseClicked

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        this.setVisible(false);
        new ReportForm().setVisible(true);
    }//GEN-LAST:event_lblExitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblheadForm;
    private java.awt.ScrollPane scrollPane1;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    // End of variables declaration//GEN-END:variables
}
