/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import design.DBConn;
import java.awt.Desktop;
import java.io.File;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Etti
 */
public class studioDetails extends javax.swing.JFrame {

    ResultSet result = null;
    JFrame form;

    /**
     * Creates new form PlaceDetails
     */
    public studioDetails(JFrame form, Integer lNumber) {
        this.form = form;
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        System.err.println(lNumber);
        if (lNumber == 10) {
            try {
                ResultSet result = DBConn.query("SELECT recordingStudio.* \n"
                        + "FROM recordingStudio\n");
                ResultSetMetaData rsmetadate = result.getMetaData();
                int columns = rsmetadate.getColumnCount();
                System.err.println("columns: " + columns);
                DefaultTableModel dtm = new DefaultTableModel();
                Vector columns_name = new Vector();
                Vector data_rows = new Vector();

                for (int i = 1; i <= columns; i++) {
                    columns_name.addElement(rsmetadate.getColumnName(i));
                }
                dtm.setColumnIdentifiers(columns_name);

                while (result.next()) {
                    data_rows = new Vector();
                    for (int j = 1; j <= columns; j++) {
                        data_rows.addElement(result.getString(j));
                    }
                    dtm.addRow(data_rows);
                }
                jTable1.setModel(dtm);

            } catch (Exception e) {
                Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, e);
            }
        }
        try {
            ResultSet result = DBConn.query("SELECT recordingStudio.* \n"
                    + "FROM recordingStudio\n"
                    + "WHERE recordingStudio.studioNumber=" + lNumber);
            ResultSetMetaData rsmetadate = result.getMetaData();
            int columns = rsmetadate.getColumnCount();
            System.err.println("columns: " + columns);
            DefaultTableModel dtm = new DefaultTableModel();
            Vector columns_name = new Vector();
            Vector data_rows = new Vector();

            for (int i = 1; i <= columns; i++) {
                columns_name.addElement(rsmetadate.getColumnName(i));
            }
            dtm.setColumnIdentifiers(columns_name);

            while (result.next()) {
                data_rows = new Vector();
                for (int j = 1; j <= columns; j++) {
                    data_rows.addElement(result.getString(j));
                }
                dtm.addRow(data_rows);
            }
            jTable1.setModel(dtm);

        } catch (Exception e) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        head = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        waze = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        head.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        head.setForeground(new java.awt.Color(255, 255, 255));
        head.setText("studio Details");
        getContentPane().add(head, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Place Number", "Place Name", "Adderss", "E-mail", "Phone", "Google-Maps", "capacity"
            }
        ));
        jTable1.setCellSelectionEnabled(true);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setRowHeight(25);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 540, 50));

        waze.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/waze.jpg"))); // NOI18N
        waze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wazeActionPerformed(evt);
            }
        });
        getContentPane().add(waze, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 40, 30));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download (4).jpg"))); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 30, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download (3).jpg"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 30, 30));

        jButton1.setText("show photo");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 100, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back-button_1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 110, 40));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.jpg"))); // NOI18N
        bg.setMaximumSize(new java.awt.Dimension(640, 500));
        bg.setMinimumSize(new java.awt.Dimension(640, 500));
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
        form.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        try {
            File f = new File("C:\\Users\\Etti\\Documents\\studioOne.jpg");
            Desktop d = Desktop.getDesktop();
            d.open(f);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton1MouseClicked

    private void wazeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wazeActionPerformed
        try {
            String URL = "https://www.waze.com/he/livemap";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_wazeActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        design.Design.player.close();  
    }//GEN-LAST:event_jButton3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel head;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton waze;
    // End of variables declaration//GEN-END:variables
}
