/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Etti
 */
public class watchStudio extends javax.swing.JFrame {

    private String sql_addStudioTofree;
    public static int next = 0;
    private static final String dbc = "jdbc:ucanaccess://src/DB.accdb;COLUMNORDER=DISPLAY";
    private static final String Studios = "SELECT recordingStudio.studioName, recordingStudio.address, recordingStudio.mail, recordingStudio.phoneNumber, recordingStudio.about\n"
            + "FROM recordingStudio;";
    public static String id = null;

    /**
     * Creates new form watchStudio
     */
    public watchStudio(String id) {
        this.id = id;
        System.err.println("" + id);
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        showStudio();

    }

    public int numberOfStudios() {
        int num = 0;
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            try (Connection conn = DriverManager.getConnection(dbc);
                    PreparedStatement stmt = conn.prepareStatement(Studios);
                    ResultSet rs = stmt.executeQuery()) {
                while (rs.next()) {
                    num++;
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
        return num;
    }

    public void showStudio() {
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            try (Connection conn = DriverManager.getConnection(dbc);
                    PreparedStatement stmt = conn.prepareStatement(Studios);
                    ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    this.studioName.setText(rs.getString(1));
                    this.studioAddress.setText(rs.getString(2));
                    this.phone.setText(rs.getString(4));
                    this.about.setText(rs.getString(5));

                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }

    }

    public void showNextStudio() {
        int count = 0;
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            try (Connection conn = DriverManager.getConnection(dbc);
                    PreparedStatement stmt = conn.prepareStatement(Studios);
                    ResultSet rs = stmt.executeQuery()) {
                while (rs.next()) {

                    this.studioName.setText(rs.getString(1));
                    this.studioAddress.setText(rs.getString(2));
                    this.phone.setText(rs.getString(4));
                    this.about.setText(rs.getString(5));

                    if (count == next) {
                        break;
                    }
                    count++;
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        head = new javax.swing.JLabel();
        bak = new javax.swing.JButton();
        studioAddress = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        about = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        studioName = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        addRoom = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        addStudioToFree = new javax.swing.JButton();
        bg = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        head.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        head.setForeground(new java.awt.Color(255, 255, 255));
        head.setText("studio's Details");
        getContentPane().add(head, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 220, 40));

        bak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back-button_1.jpg"))); // NOI18N
        bak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bakMouseClicked(evt);
            }
        });
        getContentPane().add(bak, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 100, 40));
        getContentPane().add(studioAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 130, -1));

        about.setColumns(20);
        about.setRows(5);
        jScrollPane2.setViewportView(about);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/prev.png"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 30, 30));
        getContentPane().add(studioName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 130, -1));
        getContentPane().add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 130, -1));

        addRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/next.png"))); // NOI18N
        addRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addRoomMouseClicked(evt);
            }
        });
        getContentPane().add(addRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 30, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download (3).jpg"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 30, 30));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download (4).jpg"))); // NOI18N
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 30, 30));

        jButton3.setText("add Room");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 100, -1));

        addStudioToFree.setText("addToFreelaer");
        addStudioToFree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addStudioToFreeMouseClicked(evt);
            }
        });
        getContentPane().add(addStudioToFree, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.jpg"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 580, 340));
        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 540, 100));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        getContentPane().add(jTable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addRoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addRoomMouseClicked
        if (next < numberOfStudios() - 1) {
            next++;
        }
        showNextStudio();        // TODO add your handling code here:
    }//GEN-LAST:event_addRoomMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        if (next > 0) {
            next--;
        }
        showNextStudio();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void addStudioToFreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addStudioToFreeMouseClicked
        try {//insert new artist
            sql_addStudioTofree = "INSERT INTO freelancerInStudio([freelancerId])VALUES (?)";
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            try (Connection conn = DriverManager.getConnection(dbc);
                    PreparedStatement stmt = conn.prepareStatement(sql_addStudioTofree);) {
                {
                    stmt.setString(1, id);
                    stmt.executeUpdate();
                    int n = stmt.getUpdateCount();
                    System.out.println(n + "studio inserted");
                    if (n == 1) {
                        JOptionPane.showMessageDialog(null, "studio inserted");
                    } else {
                        JOptionPane.showMessageDialog(null, "studio not inserted");
                    }
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_addStudioToFreeMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        this.setVisible(false);
        new addRoom(studioName.getText()).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void bakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bakMouseClicked
        this.setVisible(false);
        new navigtionRepForm().setVisible(true);
    }//GEN-LAST:event_bakMouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        design.Design.player.close();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea about;
    private javax.swing.JButton addRoom;
    private javax.swing.JButton addStudioToFree;
    private javax.swing.JButton bak;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel head;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField studioAddress;
    private javax.swing.JTextField studioName;
    // End of variables declaration//GEN-END:variables
}
